### ISSUE TITLE
SQLBDC2019: Module 00: Never told when to install DSVM

### ISSUE THREAD

**Issue by amthomas46** [BuckWoody/working#11]
Am I supposed to create one? It's mentioned twice but I'm never explicitly told to create one or when I should use it

<img width="440" alt="image" src="https://user-images.githubusercontent.com/28786161/51283089-de32b080-199b-11e9-94a3-0b9c69a4c2e0.png">

**Comment by BuckWoody** [comment]
I mention how to use a VM at the top of the article, but I do call this out: 
"The instructions that follow are the same for either a "base metal" workstation or laptop, or a Virtual Machine."

DBA's are more used to installing things locally, so unlike our other courses they probably won't do a VM.
