### ISSUE TITLE
SQLBDC2019: Module 00: Further Study Links

### ISSUE THREAD

**Issue by amthomas46** [BuckWoody/working#12]
I can't decide what the link for further study should be.. Maybe you link to two "Official Documentation for Microsoft's recommended big data tools" --> https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-mssqlctl?view=sqlallproducts-allversions 
And "Official Documentation for installing mssqlctl" --> https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-mssqlctl?view=sqlallproducts-allversions

**Comment by BuckWoody** [comment]
Since this is just a set of tasks to prep them for the course, I will leave this at the concepts level. I will explore this further in the Installation and Configuration section.
