### ISSUE TITLE
SQLBDC2019: Module 00: Windows Update from Powershell

### ISSUE THREAD

**Issue by amthomas46** [BuckWoody/working#13]
<img width="595" alt="image" src="https://user-images.githubusercontent.com/28786161/51283139-15a15d00-199c-11e9-87dd-47430e8575b6.png">

Not exactly sure if this is an Anna problem or a script problem?

**Comment by BuckWoody** [comment]
If you were doing this on a VM, that's expected. I'll update the section to note.
