### ISSUE TITLE
SQLBDC2019: Module 01: mssqlctl reference

### ISSUE THREAD

**Issue by amthomas46** [BuckWoody/working#16]
"The mssqlctl command-line utility is written in Python and can be installed on your workstation using the pip command in Python. You will see how to install this utility in the Planning, Installation and Configuration module." This was done in the prereqs, not sure if you want to remove this or leave it.

**Comment by BuckWoody** [comment]
I have them do an install in the Pre-Reqs with no explanation - and then we talk about the installation in depth since it's a fairly involved process. It's that longer explanation I'll be covering.
