### ISSUE TITLE
Module 01 prereq link does not work

### ISSUE THREAD

**Issue by ctesta-oneillmsft** [BuckWoody/working#24]
***All links that point to pre-requisites do not work and should be checked globally

In the following page
https://github.com/BuckWoody/working/blob/master/SQL2019BDC-Unstaged/SQL2019BDC/01%20-%20The%20Big%20Data%20Landscape.md

The link in the text
(Make sure you check out the prerequisites page before you start. ......

and in the following section

Activity: Install Class Environment on AKS
Steps
 Ensure that you have completed all prerequisites.

The link does not work

**Comment by BuckWoody** [comment]
Corrected.
