### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by ctesta-oneillmsft** [BuckWoody/working#25]
In the file.
https://github.com/BuckWoody/working/blob/master/SQL2019BDC-Unstaged/SQL2019BDC/01%20-%20The%20Big%20Data%20Landscape.md#1-7

In the ADF section

Data Pipelines using Azure Data Factory
As described earlier, you can use various methods to ingest data ad-hoc and as-needed for your two data targets (HDFS and SQL Server Tables. A more holistic archicture is to use a Pipeline system ***tht*** can define sources, triggers and events, 

change tht to that

**Comment by ctesta-oneillmsft** [comment]
File
https://github.com/BuckWoody/working/blob/master/SQL2019BDC-Unstaged/SQL2019BDC/02%20-%20SQL%20Server%20BDC%20Components.md

Section:
2.2 SQL Server 2019 big data cluster Components

First line
The Big Data **capapbilities** for SQL Server

**Comment by BuckWoody** [comment]
Corrected. Thank you!
