### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by ctesta-oneillmsft** [BuckWoody/working#27]
File

https://github.com/BuckWoody/working/blob/master/SQL2019BDC-Unstaged/SQL2019BDC/02%20-%20SQL%20Server%20BDC%20Components.md

and 

https://github.com/BuckWoody/working/blob/master/SQL2019BDC-Unstaged/SQL2019BDC/03%20-%20Planning,%20Installation%20and%20Configuration.md

first line

In this workshop you'll cover using a Process **and and** various Platform component

**Comment by BuckWoody** [comment]
Fixed - good catch.
